import { Button, VerticalBox , LineEdit} from "std-widgets.slint";

component Settings {
    Text {
        text: "SETTINGS";
        horizontal-alignment: center;
        font-weight: 900;
        font-size: 20px;
        // color: green;
    }
}

export component AppWindow inherits Window {

    in property <string> results: "";
    in-out property <bool> opencurtain;
    callback divide-income(string);

    Settings {}
    
    // background: #14213d;
    GridLayout {
        padding: 50px;
        spacing: 10px;
        Row {
            Text {
                text: "income and expenses calculator";
                horizontal-alignment: center;
                font-weight: 900;
                font-size: 20px;
                // color: green;
            }
        }
        Row {
            income := LineEdit {
                placeholder-text: "Inkomen (loon)";
                horizontal-alignment: center;
                font-size: 16px;
                width: 200px;
                height: 35px;
                input-type: number;
            }
        }
        Row {
            LineEdit {
                placeholder-text: "Ander inkomen";
                horizontal-alignment: center;
                font-size: 16px;
                width: 200px;
                height: 35px;
                input-type: number;
            }
        }
        Row {
            b1 := Button {
                text: "Bereken";
                clicked => {
                    root.opencurtain = !root.opencurtain;
                    divide-income(income.text)
                }
                primary: true;
                width: 150px;
                height: 40px;
                
            }
        }
        Row {
            b2 := Button {
                text: "Settings";
                // clicked => { Settings }
                primary: true;
                width:80px;
                height: 30px;
            }
        }
        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }

                    // L
                    Rectangle {
                        // background: #333333;
                        x: 0;
                        width: opencurtain ? 0px : parent.width / 2;
                        height: parent.height;
                        animate width {
                            duration: 250ms; easing: ease-in;
                        }
                    }

                    // R
                    Rectangle {
                        // background: #333333;
                        x: opencurtain ? parent.width : parent.width /2;
                        width: opencurtain ? 0px : parent.width / 2;
                        height: parent.height;
                        animate width {
                            duration: 250ms; easing: ease-in;
                        }
                        animate x {
                            duration: 250ms; easing: ease-in;
                        }
                    }
                }
            }
        }
    }


    // function switchToSecondUI() {
    //     // Code to switch to the second UI file
    //     include("second_ui.slint");
    // }
}
